on:
  push:
    branches: [master]
    paths-ignore:
    - .gitignore
    - LICENSE
    - README.md
    - Rakefile
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - timeout-minutes: 1
      run: |
        docker run -v $(pwd):/checkout -w /checkout ruby:2.4-alpine3.10 sh -c "apk add git build-base vips chromium ttf-dejavu && gem update bundler && bundle install --no-cache && bundle exec ruby test.rb"
